site_name: Tiller
repo_url: https://github.com/markround/tiller/

theme: readthedocs
extra_javascript: 
  - js/extra.js

pages:
- Home: 'index.md'
- Quickstart: 'quickstart.md'
- General Usage:
  - Overview: 'general/index.md'
  - Configuration: 'general/configuration.md'
  - Setup With Docker: 'general/docker.md'
- Advanced Usage:
  - Checksums: 'advanced/checksums.md'
  - Nested Templates: 'advanced/subtemplates.md'
  - Dynamic Values: 'advanced/dynamic.md'
  - Separate Config Files: 'advanced/separate_config.md'
  - HTTP API: 'advanced/api.md'
  - Exec On Write: 'advanced/exec_on_write.md'
- Common Issues: 'general/faq.md'
- Plugins:
  - Overview: 'plugins/index.md'
  - Available Plugins:
      - Ansible Vault: 'plugins/ansible_vault.md'
      - Consul: 'plugins/consul.md'
      - Defaults: 'plugins/defaults.md'
      - Environment: 'plugins/environment.md'
      - Environment JSON: 'plugins/environment_json.md'
      - External File: 'plugins/external_file.md'
      - File: 'plugins/file.md'
      - HTTP: 'plugins/http.md'
      - Random: 'plugins/random.md'
      - Hashicorp Vault: 'plugins/vault.md'
      - XML File: 'plugins/xml_file.md'
      - Zookeeper: 'plugins/zookeeper.md'
- Developer Information: 'developers.md'
- Further Reading: 'resources.md'
- About:
  - Changelog: 'changelog.md'
  - License: 'license.md'
  - Thanks: 'general/thanks.md'
  - Support: 'general/support.md'
