name: Ruby

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.5.3, 3.1.3]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: ${{ matrix.ruby }}
#      - name: Update bundler
#        run: gem update bundler
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
